### ISSUE TITLE
Showing similar message all the time

### ISSUE THREAD

**Issue by cngondo** [BrianLusina/Chatterbox-app#1]
Check out the [ChatsFragment.java](https://github.com/BrianLusina/Chatterbox-app/blob/master/app/src/main/java/com/chatterbox/chatterbox/drawerfragments/ChatsFragment.java) class where you have the `prepareMockChatItems()` method. You may be calling this class which sets the message, using the setters from the `ChatsModel` class.

Kindly get the text from `EditText` layout at [chatsitem_layout.xml](https://github.com/BrianLusina/Chatterbox-app/blob/master/app/src/main/java/com/chatterbox/chatterbox/drawerfragments/ChatsFragment.java) using the `getText().toString()` methods. Then display that text to the `ListView`.

**Comment by BrianLusina** [comment]
`ChatsFragment.java` class is not the one being displayed the one that is being displayed is `MainActivity.java` class, `ChatsFragment` is displaying mock data for  the most recent chats of the user of which if ones is clicked they are directed to the `MainActivity` which displays the chat thread for that recent chat.

**Comment by cngondo** [comment]
Did you find a workaround on this?
